const industryMap = {
  internet: '互联网',
  hr: '人力资源',
  supply_chain: '供应链/物流',
  agriculture: '农林牧渔',
  manufacturing: '制造',
  chemical: '化工/环保/能源',
  healthcare: '医疗健康',
  consulting: '咨询/翻译',
  marketing: '市场/公关/广告',
  media: '影视/传媒',
  real_estate: '房地产/建筑',
  education: '教育培训',
  services: '服务',
  law: '法律',
  electronics: '电子/通信',
  design: '设计',
  audit: '财务/审计/税务',
  hospitality: '酒店/旅游',
  trade: '采购/贸易',
  sales: '销售',
  restaurant: '餐饮',
  finance: '金融',
  other: '其他行业',
}
const jobOptions = {
  internet: ['后端开发', '前端开发', '移动开发'],
  hr: ['HR经理', '招聘专员'],
  supply_chain: ['物流经理', '供应链经理'],
  agriculture: ['农场经理', '农业顾问'],
  manufacturing: ['生产经理', '设备维护工程师'],
  healthcare: ['医生', '护士', '医疗顾问'],
  consulting: ['管理咨询', '市场咨询'],
  marketing: ['市场营销经理', '品牌经理'],
  media: ['导演', '编剧'],
  real_estate: ['房地产销售', '地产项目经理'],
  education: ['教师', '教育顾问'],
  services: ['客户服务代表', '服务经理'],
  law: ['律师', '法务专员'],
  electronics: ['电子工程师', '通信工程师'],
  design: ['UI设计师', '平面设计师'],
  audit: ['财务经理', '审计员'],
  hospitality: ['酒店经理', '旅游顾问'],
  trade: ['采购经理', '供应链经理'],
  sales: ['销售经理', '销售代表'],
  restaurant: ['餐厅经理', '厨师'],
  finance: ['资产评估师', '投资经理'],
  other: ['其他'],
}

const skillsOptions = {
  internet: ['JavaScript', 'Python', 'React', 'Node.js'],
  hr: ['招聘技能', '员工管理'],
  supply_chain: ['物流管理', '供应链优化'],
  agriculture: ['农业知识', '农田管理'],
  manufacturing: ['生产线管理', '设备维护'],
  healthcare: ['医学知识', '护理技能'],
  consulting: ['战略规划', '市场研究'],
  marketing: ['数字营销', '品牌推广'],
  media: ['视频编辑', '剧本创作'],
  real_estate: ['房地产管理', '市场营销'],
  education: ['教育理论', '课程设计'],
  services: ['客户沟通', '问题解决'],
  law: ['合同法', '法律咨询'],
  electronics: ['电子电路', '通信技术'],
  design: ['Photoshop', 'Sketch', 'UI/UX设计'],
  audit: ['财务分析', '税务规划'],
  hospitality: ['客户服务', '酒店管理'],
  trade: ['采购管理', '供应链管理'],
  sales: ['销售技巧', '市场拓展'],
  restaurant: ['烹饪技巧', '餐厅管理'],
  finance: ['资产评估', '风险评估'],
  other: ['其他'],
}
const cities = {
  北京: ['北京市'],
  上海: ['上海市'],
  湖南: ['长沙', '岳阳', '株洲'],
  广东: ['广州', '深圳', '珠海'],
}
export default { industryMap, jobOptions, skillsOptions,cities }
